services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: <database_name>
      POSTGRES_USER: <database_username>
      POSTGRES_PASSWORD: <database_password>
    ports:
      - "<database_port>:<database_port>"

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "<redis_port>:<redis_port>"
  web:
    build: .
    command: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=<database_name>
      - POSTGRES_USER=<database_username>
      - POSTGRES_PASSWORD=<database_password>
      - POSTGRES_HOST=db
      - POSTGRES_PORT=<database_port>
      - REDIS_PORT=<redis_port>
      - REDIS_HOST=redis

volumes:
  postgres_data:
